name: Run tests on any Push event
# Will run on every push event in repository
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      # Code checkout
      - uses: actions/checkout@master
      # Setup Python
      - uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Make storage dir for tests
        run: sudo mkdir -p /storage # needs for testing
      - name: Change storage dir owner
        run: sudo chown -R runner /storage
      - name: Run tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DBHOST_DEV: ${{ secrets.DBHOST_DEV }}
          CODECLIMATE_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TEST_REPORTER_ID }}
        run: pytest -vrP
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v2.7.1
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DBHOST_DEV: ${{ secrets.DBHOST_DEV }}
          CODECLIMATE_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TEST_REPORTER_ID }}
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TEST_REPORTER_ID }}
        with:
          coverageCommand: coverage run -m pytest .
          debug: true
