name: Run tests on any Push event
# Запуск при любом push евенте в любой ветке, за исключением релизных тэгов.
# Они будт тестироваться перед сборкой
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      # Чекаутим код
      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install -r requirements.txt
      - name: Make storage dir for tests
        run: sudo mkdir -p /storage # needs for testing
      - name: Run tests
        env: # Or as an environment variable
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DBHOST_DEV: ${{ secrets.DBHOST_DEV }}
        run: pytest -v
        # run: coverage run src/tests.py
      # - name: Tests report
      #   run: coverage report